# Generated by Django 4.1.3 on 2022-12-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('proce', models.DecimalField(decimal_places=2, default=99.99, max_digits=15)),
            ],
        ),
    ]
